services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  server1:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx ./index.ts
    depends_on:
      - mongo

  server2:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx ./index.ts
    depends_on:
      - mongo

  server3:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx ./index.ts
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
